# concurrency test, switch to ec2 later

---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  security_group_ids: [ "<%= ENV['AWS_SGROUP_ID'] %>" ]
  region: us-west-2
  availability_zone: b
  instance_type: t2.micro
  associate_public_ip: true
#  require_chef_omnibus: true

transport:
  ssh_key: provision.key
  connection_timeout: 10
  connection_retries: 10

provisioner:
  name: salt_solo
  formula: docker
  salt_install: bootstrap
  salt_bootstrap_options: -P git v2015.8.4
  pillars:
    top.sls:
      base:
        '*':
          - docker


suites:
  - name: compose
    provisioner:
      pillars-from-files:
        docker.sls: pillar.cloud.example
      state_top:
        base:
          '*':
            - docker.compose.install

  - name: engine
    provisioner:
      pillars-from-files:
        docker.sls: pillar.cloud.example
      state_top:
        base:
          '*':
            - docker.engine.install
            - docker.engine.users

  - name: csengine
    provisioner:
      pillars-from-files:
        docker.sls: pillar.cs.cloud.example
      state_top:
        base:
          '*':
            - docker.engine.install
            - docker.engine.users

platforms:

  - name: precise
    transport:
      username: ubuntu
    driver:
      image_search:
       name: "ubuntu/images/hvm/ubuntu-precise-12.04-amd64-server-*"

  - name: trusty
    transport:
      username: ubuntu
    driver:
      image_search:
          name: "ubuntu/images/hvm/ubuntu-trusty-14.04-amd64-server-*"

